version: "3.8"
services:
  proxy:
    image: santiagopereyramarchetti/proxy:1.2
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - nginx
  
  frontend:
    image: santiagopereyramarchetti/frontend:1.2
    container_name: frontend
    restart: unless-stopped

  nginx:
    image: santiagopereyramarchetti/nginx:1.2
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - api

  api:
    image: santiagopereyramarchetti/api:1.2
    container_name: api
    env_file:
      - .env
      - .env.ini
    depends_on:
      - mysql
      - redis

  mysql:
    image: santiagopereyramarchetti/mysql:1.2
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./mysqldata:/var/lib/mysql
    env_file:
      - .env.mysql

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redisdata:/data

  # inicialization:
  #   image: santiagopereyramarchetti/inicialization:1.2
  #   container_name: inicialization
  #   restart: no
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   env_file:
  #     - .env.ini.build
  #   depends_on:
  #     - mysql
  #     - redis
  #     - api